### PR TITLE
use outcome from TestCase instead of TestResult

### PR DESCRIPTION
**Pull request by clouddra**
Fixes https://github.com/reportportal/agent-js-playwright/issues/73 by using the correct field to determine retry status.

This is the canonical method based on the playwright [codebase](https://github.com/microsoft/playwright/blob/62e4e80599efc00a799a389ee4be76c74c9f172b/packages/playwright-test/src/reporters/base.ts#L226).

### CODE REVIEW

**Comment by clouddra** [comment]
Hi is there anything missing that I need to do to get this merged in?

**Comment by AmsterGet** [comment]
Hello @clouddra !
Sorry, I was on vacation, I'll finish the review this week.
Thank you very much for contribution!

**Comment by clouddra** [comment]
any updates on this?

**Comment by AmsterGet** [comment]
Hello @clouddra !
Sorry for the delay - there was a long period of illness, and then holidays.
I'm looking at your PR right now and I have an idea - handle test case status entirely based on `outcome`.
I will try to get back to you tomorrow.
Thank you for your patience.

**Review by AmsterGet — APPROVED** [review]

**Comment by AmsterGet** [comment]
@clouddra sorry for such late response.
I've merged it, finally.
Thank you very much for your efforts.

**Pull request merged**
